### ISSUE TITLE
Implement admin delete for the platform

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-ops#144]
### Implement Admin Delete for Platform

**Purpose:** Give admin users the ability to delete files in the redwood storage system.

Design notes [[Link](https://docs.google.com/spreadsheets/d/1-0AqSQGpKAV7HSXG37wM5Ak4WDbE48wOzMeI8hU7JYE/edit#gid=1576747757)]
Client lssue: [DCC-Ops #146](https://github.com/BD2KGenomics/dcc-ops/pull/146)
Server Issue: [DCC-Metadata-Indexer #94](https://github.com/BD2KGenomics/dcc-metadata-indexer/issues/94)
#### Basic Functionality

- [x] Implement Basic Delete Functionality
- [x] Implement Delete History

#### Metadata Housekeeping

- [x] Create a data access object class to handle redwood-metadata-db
- [x] Code a way to edit the deleted file's metadata.json
- [x] Implement code that will edit metadata listing endpoints

#### Boardwalk modifications
 (Issue: https://github.com/BD2KGenomics/dcc-metadata-indexer/issues/94)

- [x] Modify File Browser to ignore deleted files
- [x] Modify Metadata Indexer to ignore deleted files
- [x] Modify Invoicing Indexer to ignore deleted files

**Comment by kozbo** [comment]
Step 1 is #148

**Comment by GPelayo** [comment]
Made pull request at https://github.com/BD2KGenomics/dcc-storage/pull/28

**Comment by kozbo** [comment]
design notes https://docs.google.com/spreadsheets/d/1-0AqSQGpKAV7HSXG37wM5Ak4WDbE48wOzMeI8hU7JYE/edit#gid=1576747757
